#! /bin/bash -ex

# Build script for a VMOD uuid el7 RPM
# to be run in the rpmbuild/centos7 docker container.

# Env variables VERSION and RELEASE MUST be set in the docker invocation.
# DIST is set by the rpmbuild/centos7 container.

# The directory mounted to /srv MUST contain these files:
# - this script (named pkg)
# - VMOD uuid tarball (vmod-uuid-$VERSION.tar.gz), built by 'make distcheck'
# - RPM spec file (vmod-uuid.spec)
# - yum repo config for varnish66@packagecloud (varnishcache_varnish66.repo)
#   (see https://packagecloud.io/varnishcache/varnish66/install#manual-rpm)

# So this is a sample docker invocation:
#
# $ docker run -t -v $PWD:/srv -e VERSION=1.2.3 -e RELEASE=4711 \
#	rpmbuild/centos7 /srv/pkg

# At the end of the run, binary, source and debuginfo RPMs are in the
# directory mounted to /srv.

if [ -z $VERSION ]; then
   echo "Env variable VERSION MUST be set"
   exit 1
fi

if [ -z $RELEASE ]; then
   echo "Env variable RELEASE MUST be set"
   exit 1
fi

# delete the peculiar macros from the rpmbuild/centos7 image
rm /home/builder/.rpmmacros

# set up the build environment
cd /home/builder
mkdir -p rpmbuild/{BUILD,BUILDROOT,RPMS,SOURCES,SPECS,SRPMS}
cp /srv/vmod-uuid.spec rpmbuild/SPECS
cp /srv/vmod-uuid-maxwait-${VERSION}.tar.gz rpmbuild/SOURCES

# update the build env
set +e
sudo yum check-update -y -q
set -e
sudo yum upgrade -y -q

# set uplex repo for varnish-maxwait and VMOD re
sudo yum-config-manager --add-repo https://pkg.uplex.de/rpm/7/uplex-varnish/x86_64/

# install epel7 repo
sudo yum install -y -q \
     https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm

# build requirements
sudo yum install --nogpgcheck -y -q varnish-maxwait-devel
sudo yum install -y -q uuid-devel pkgconfig make gcc python-docutils

# build RPMs
rpmbuild -ba -D "dist .${DIST}" \
         -D "_version ${VERSION}" \
         -D "_release ${RELEASE}" \
         rpmbuild/SPECS/vmod-uuid.spec

sudo cp rpmbuild/RPMS/*/* /srv
sudo cp rpmbuild/SRPMS/* /srv
